### PR TITLE
Fix GH CI/CD, update libraries and remove old pinning, make 'Update bundle' workflow usable.

### PR DESCRIPTION
**Pull request by taurus-forever**
* add missing update_bundle.py and fix pathes to bundle.yaml
* rename GH CI/CD 'Update bundle' to provide short badge
* add badges to show them on https://releases.juju.is/
* remove old and no longer necessary pinning
* fix reviewers list to avoid GH warnings
* Bump juju-agent to the latest 2.9.42
* Update tox config and add pyproject.toml from kafka-bundle
* Update charm libraries
* Move charmcraft files in a common places (to make `charmcraft fetch-libs` happy)
*  add LICENSE file
* add library check CI test
* abort old tests on new commit pushed to PR
* remove on_pull_request.yaml as unnecessary complexity

### CODE REVIEW

**Comment by taurus-forever** [comment]
@marcoppenheimer any ideas what can be wrong with a kafka->zookeeper communication here?
It looks like Kafka [cannot execute](https://github.com/canonical/kafka-k8s-bundle/actions/runs/4370149370/jobs/7644865787#step:4:160) `srvr` requests:

```
  File "/var/lib/juju/agents/unit-kafka-k8s-0/charm/lib/charms/zookeeper/v0/client.py", line 447, in srvr
    response = self._run_4lw_command("srvr")
  File "/var/lib/juju/agents/unit-kafka-k8s-0/charm/lib/charms/zookeeper/v0/client.py", line 422, in _run_4lw_command
    return self.client.command(command.encode())
  File "/var/lib/juju/agents/unit-kafka-k8s-0/charm/venv/kazoo/client.py", line 735, in command
    result = sock.recv(8192)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by deusebio** [comment]
This bundle has not yet been in the scope of current work so far. We need to first port features from vm to k8s (for both kafka and zookeeper) to have them stable first, and then make sure the bundles work properly. 

We should start working on migrating features from vm to k8s in the next pulse, so I'd just hold off to dig deeper into this until we have stable k8s component for both kafka and zk. 

We could keep the PR open as all the changes are fine and sensible, with the aim to come back here once we have underlying components that are stable to make sure everything works as expected

**Comment by taurus-forever** [comment]
> We could keep the PR open as all the changes are fine and sensible, with the aim to come back here once we have underlying components that are stable to make sure everything works as expected

As you wish. The issues here were stopped due to migration of all bundles to new [Canonical DP Bot](https://github.com/canonical-data-platform-bot) => PR prepared otherwise it was impossible to test/update bundle YAML file using new bot.

**Comment by taurus-forever** [comment]
Just for the history: zookeeper issue [traced down and reported](https://warthogs.atlassian.net/browse/DPE-1481).

**Comment by deusebio** [comment]
closing as stable and not relevant any longer

**Pull request closed without merging**
